service: quarkus-aws-integration

provider:
  name: aws
  stage: dev
  region: us-east-1
  versionFunctions: false
  memorySize: 512
  timeout: 60
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"
  environment:
    SERVICE_REGION: ${self:provider.region}
    QUEUE_URL:
      Ref: QuarkusQueue

package:
  individually: true

functions:
  ApiJvm:
    runtime: java8
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    package:
      artifact: target/quarkus-sqs-test-1.0-SNAPSHOT-runner.jar
    events:
      - http:
          path: /jvm/{any+}
          method: ANY

  ApiNative:
    runtime: provided
    handler: native.handler
    package:
      artifact: target-native/function.zip
    environment:
      DISABLE_SIGNAL_HANDLERS: true
    events:
      - http:
          path: /native/{any+}
          method: ANY

resources:
  Resources:
    QuarkusQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:service}-queue
        MessageRetentionPeriod: 300

plugins:
  - serverless-export-env